In [3]:
import pandas as pd
df = pd.read_csv('ItemParameterEstimates.csv')

df

,question_id,skill_id,discriminability,difficulty,guessing,inattention,discriminability_error,difficulty_error,guessing_error,inattention_error,auc_roc,optimal_threshold,tpr,tnr,skill_optimal_threshold,student_mean_accuracy,sample_size,date_created,version
0,1273d5659acf,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.666667,3,2024-05-03,220240429
1,25403a3df661,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.714286,7,2024-05-03,220240429
2,3c68a603a797,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1,2024-05-03,220240429
3,42591ca4cc3e,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,3,2024-05-03,220240429
4,5bc2ea103a10,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.714286,7,2024-05-03,220240429
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97506,fc554264b8ce,bc7b5e8e21eae311b64a005056801da1,100.000000,-0.033391,2.645657e-12,1.000000,23.832253,0.002800,0.075765,0.043118,0.933879,0.571050,0.953846,0.829787,0.591692,0.734463,177,2024-04-29,220240429
97507,fc8085d91702,bc7b5e8e21eae311b64a005056801da1,5.740566,-0.214509,1.701641e-16,1.000000,9.973790,0.467930,1.332327,0.312270,0.575930,0.791062,0.276382,0.898305,0.591692,0.771318,258,2024-04-29,220240429
97508,fd6f9267d809,bc7b5e8e21eae311b64a005056801da1,100.000000,-0.032746,4.317059e-02,0.968259,25.180285,0.003402,0.092751,0.033486,0.874103,0.702516,0.904523,0.732143,0.591692,0.780392,255,2024-04-29,220240429
97509,fe03fa7db971,bc7b5e8e21eae311b64a005056801da1,100.000000,-0.008714,3.049256e-13,1.000000,28.172949,0.003005,0.079474,0.078663,0.899364,0.507087,0.863158,0.802198,0.591692,0.510753,186,2024-04-29,220240429
97510,fe7b31d0489c,bc7b5e8e21eae311b64a005056801da1,31.832646,-0.016067,4.063628e-20,0.881256,15.227210,0.016615,0.184531,0.123983,0.735545,0.510801,0.729730,0.654545,0.591692,0.502262,221,2024-04-29,220240429

In [ ]:
df.to_csv('ItemParameterEstimates_bu.csv',index=False)

In [4]:
def add_decimal(number):
    number_str = str(number)
    return float(number_str[0] + '.' + number_str[1:])

# Apply the function to the 'version' column
df['version'] = df['version'].apply(add_decimal)
df

,question_id,skill_id,discriminability,difficulty,guessing,inattention,discriminability_error,difficulty_error,guessing_error,inattention_error,auc_roc,optimal_threshold,tpr,tnr,skill_optimal_threshold,student_mean_accuracy,sample_size,date_created,version
0,1273d5659acf,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.666667,3,2024-05-03,2.202404
1,25403a3df661,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.714286,7,2024-05-03,2.202404
2,3c68a603a797,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1,2024-05-03,2.202404
3,42591ca4cc3e,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,3,2024-05-03,2.202404
4,5bc2ea103a10,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.714286,7,2024-05-03,2.202404
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97506,fc554264b8ce,bc7b5e8e21eae311b64a005056801da1,100.000000,-0.033391,2.645657e-12,1.000000,23.832253,0.002800,0.075765,0.043118,0.933879,0.571050,0.953846,0.829787,0.591692,0.734463,177,2024-04-29,2.202404
97507,fc8085d91702,bc7b5e8e21eae311b64a005056801da1,5.740566,-0.214509,1.701641e-16,1.000000,9.973790,0.467930,1.332327,0.312270,0.575930,0.791062,0.276382,0.898305,0.591692,0.771318,258,2024-04-29,2.202404
97508,fd6f9267d809,bc7b5e8e21eae311b64a005056801da1,100.000000,-0.032746,4.317059e-02,0.968259,25.180285,0.003402,0.092751,0.033486,0.874103,0.702516,0.904523,0.732143,0.591692,0.780392,255,2024-04-29,2.202404
97509,fe03fa7db971,bc7b5e8e21eae311b64a005056801da1,100.000000,-0.008714,3.049256e-13,1.000000,28.172949,0.003005,0.079474,0.078663,0.899364,0.507087,0.863158,0.802198,0.591692,0.510753,186,2024-04-29,2.202404
97510,fe7b31d0489c,bc7b5e8e21eae311b64a005056801da1,31.832646,-0.016067,4.063628e-20,0.881256,15.227210,0.016615,0.184531,0.123983,0.735545,0.510801,0.729730,0.654545,0.591692,0.502262,221,2024-04-29,2.202404

In [5]:
df.to_csv('ItemParameterEstimates.csv',index=False)

In [7]:
import pandas as pd
df = pd.read_csv('ItemParameterEstimates.csv')

df

,question_id,skill_id,discriminability,difficulty,guessing,inattention,discriminability_error,difficulty_error,guessing_error,inattention_error,auc_roc,optimal_threshold,tpr,tnr,skill_optimal_threshold,student_mean_accuracy,sample_size,date_created,version
0,1273d5659acf,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.666667,3,2024-05-03,2.202404
1,25403a3df661,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.714286,7,2024-05-03,2.202404
2,3c68a603a797,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1,2024-05-03,2.202404
3,42591ca4cc3e,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,3,2024-05-03,2.202404
4,5bc2ea103a10,rhkurjzj,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.714286,7,2024-05-03,2.202404
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97506,fc554264b8ce,bc7b5e8e21eae311b64a005056801da1,100.000000,-0.033391,2.645657e-12,1.000000,23.832253,0.002800,0.075765,0.043118,0.933879,0.571050,0.953846,0.829787,0.591692,0.734463,177,2024-04-29,2.202404
97507,fc8085d91702,bc7b5e8e21eae311b64a005056801da1,5.740566,-0.214509,1.701641e-16,1.000000,9.973790,0.467930,1.332327,0.312270,0.575930,0.791062,0.276382,0.898305,0.591692,0.771318,258,2024-04-29,2.202404
97508,fd6f9267d809,bc7b5e8e21eae311b64a005056801da1,100.000000,-0.032746,4.317059e-02,0.968259,25.180285,0.003402,0.092751,0.033486,0.874103,0.702516,0.904523,0.732143,0.591692,0.780392,255,2024-04-29,2.202404
97509,fe03fa7db971,bc7b5e8e21eae311b64a005056801da1,100.000000,-0.008714,3.049256e-13,1.000000,28.172949,0.003005,0.079474,0.078663,0.899364,0.507087,0.863158,0.802198,0.591692,0.510753,186,2024-04-29,2.202404
97510,fe7b31d0489c,bc7b5e8e21eae311b64a005056801da1,31.832646,-0.016067,4.063628e-20,0.881256,15.227210,0.016615,0.184531,0.123983,0.735545,0.510801,0.729730,0.654545,0.591692,0.502262,221,2024-04-29,2.202404