In [14]:
import pandas as pd
df = pd.read_csv('ItemParameterEstimates20240105.csv')
df

,question_id,skill_or_subskill_id,discriminability,difficulty,guessing,inattention,discriminability_error,difficulty_error,guessing_error,inattention_error,auc_roc,optimal_threshold,tpr,tnr,sample_size,date_created,version
0,01ca3ac546e3,bc7b5e8e21eae311b64a005056801da1,70.387182,0.022767,3.486736e-13,0.957030,3.668211,0.000988,0.009955,0.027645,0.832915,0.261169,0.789720,0.712317,9247,2024-01-05,1.2
1,03d6a454c3de,bc7b5e8e21eae311b64a005056801da1,69.032380,-0.000382,5.448425e-14,0.990786,4.273642,0.000999,0.023988,0.016896,0.814612,0.636964,0.782982,0.680363,6625,2024-01-05,1.2
2,041762988fc6,bc7b5e8e21eae311b64a005056801da1,29.337754,-0.027698,8.433487e-02,1.000000,2.514609,0.003375,0.036890,0.021804,0.704879,0.751915,0.713770,0.583673,9133,2024-01-05,1.2
3,042be327b7d9,bc7b5e8e21eae311b64a005056801da1,70.467524,0.021816,4.002897e-11,0.966150,3.559106,0.000927,0.009961,0.025747,0.834225,0.242820,0.827655,0.670118,9352,2024-01-05,1.2
4,0451bd23ae22,bc7b5e8e21eae311b64a005056801da1,36.886380,0.016789,2.414249e-02,1.000000,3.687978,0.002981,0.040492,0.039129,0.701185,0.513246,0.577762,0.710192,5958,2024-01-05,1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106642,c9e287faf961,9c8063d82400e4119e54005056801da1,8.415374,-0.268215,4.741020e-13,0.978466,0.887805,0.023633,0.060258,0.011605,0.777819,0.877293,0.584106,0.798387,2637,2024-01-13,1.2
106643,c9fb774e480b,9c8063d82400e4119e54005056801da1,21.715597,-0.040910,5.153232e-15,0.983474,1.709024,0.004150,0.031590,0.012757,0.891011,0.659936,0.755249,0.904918,2582,2024-01-13,1.2
106644,d3dd4d74bc29,9c8063d82400e4119e54005056801da1,6.453172,-0.228860,7.228266e-16,0.987656,0.798026,0.028779,0.063965,0.017162,0.763622,0.824429,0.513929,0.859232,2629,2024-01-13,1.2
106645,d5c96706d9d6,9c8063d82400e4119e54005056801da1,8.281215,-0.198515,2.635557e-14,0.976633,0.892442,0.019438,0.050531,0.014647,0.784525,0.841281,0.528275,0.869027,2687,2024-01-13,1.2
106646,e3174b02c189,9c8063d82400e4119e54005056801da1,100.000000,-0.117890,6.006335e-20,0.966532,8.936638,0.001472,0.019913,0.004322,0.904885,0.966267,0.673239,0.943609,2751,2024-01-13,1.2

In [16]:
df['date_created'] = pd.Timestamp('2024-03-25')
df['version'] = 1.3

In [ ]:
# question_id,skill_id,discriminability,difficulty,guessing,inattention,discriminability_error,difficulty_error,guessing_error,inattention_error,auc_roc,optimal_threshold,tpr,tnr,
# skill_optimal_threshold,student_mean_accuracy,
# sample_size,date_created,version

In [17]:
df

,question_id,skill_or_subskill_id,discriminability,difficulty,guessing,inattention,discriminability_error,difficulty_error,guessing_error,inattention_error,auc_roc,optimal_threshold,tpr,tnr,sample_size,date_created,version
0,01ca3ac546e3,bc7b5e8e21eae311b64a005056801da1,70.387182,0.022767,3.486736e-13,0.957030,3.668211,0.000988,0.009955,0.027645,0.832915,0.261169,0.789720,0.712317,9247,2024-03-25,1.3
1,03d6a454c3de,bc7b5e8e21eae311b64a005056801da1,69.032380,-0.000382,5.448425e-14,0.990786,4.273642,0.000999,0.023988,0.016896,0.814612,0.636964,0.782982,0.680363,6625,2024-03-25,1.3
2,041762988fc6,bc7b5e8e21eae311b64a005056801da1,29.337754,-0.027698,8.433487e-02,1.000000,2.514609,0.003375,0.036890,0.021804,0.704879,0.751915,0.713770,0.583673,9133,2024-03-25,1.3
3,042be327b7d9,bc7b5e8e21eae311b64a005056801da1,70.467524,0.021816,4.002897e-11,0.966150,3.559106,0.000927,0.009961,0.025747,0.834225,0.242820,0.827655,0.670118,9352,2024-03-25,1.3
4,0451bd23ae22,bc7b5e8e21eae311b64a005056801da1,36.886380,0.016789,2.414249e-02,1.000000,3.687978,0.002981,0.040492,0.039129,0.701185,0.513246,0.577762,0.710192,5958,2024-03-25,1.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106642,c9e287faf961,9c8063d82400e4119e54005056801da1,8.415374,-0.268215,4.741020e-13,0.978466,0.887805,0.023633,0.060258,0.011605,0.777819,0.877293,0.584106,0.798387,2637,2024-03-25,1.3
106643,c9fb774e480b,9c8063d82400e4119e54005056801da1,21.715597,-0.040910,5.153232e-15,0.983474,1.709024,0.004150,0.031590,0.012757,0.891011,0.659936,0.755249,0.904918,2582,2024-03-25,1.3
106644,d3dd4d74bc29,9c8063d82400e4119e54005056801da1,6.453172,-0.228860,7.228266e-16,0.987656,0.798026,0.028779,0.063965,0.017162,0.763622,0.824429,0.513929,0.859232,2629,2024-03-25,1.3
106645,d5c96706d9d6,9c8063d82400e4119e54005056801da1,8.281215,-0.198515,2.635557e-14,0.976633,0.892442,0.019438,0.050531,0.014647,0.784525,0.841281,0.528275,0.869027,2687,2024-03-25,1.3
106646,e3174b02c189,9c8063d82400e4119e54005056801da1,100.000000,-0.117890,6.006335e-20,0.966532,8.936638,0.001472,0.019913,0.004322,0.904885,0.966267,0.673239,0.943609,2751,2024-03-25,1.3

In [18]:
skill_optimal_threshold=df[['skill_or_subskill_id','optimal_threshold']].groupby('skill_or_subskill_id').mean().reset_index()

skill_optimal_threshold.rename(columns={'optimal_threshold': 'skill_optimal_threshold'}, inplace=True)
skill_optimal_threshold
df = pd.merge(df, skill_optimal_threshold, on='skill_or_subskill_id', how='left')
df

,question_id,skill_or_subskill_id,discriminability,difficulty,guessing,inattention,discriminability_error,difficulty_error,guessing_error,inattention_error,auc_roc,optimal_threshold,tpr,tnr,sample_size,date_created,version,skill_optimal_threshold
0,01ca3ac546e3,bc7b5e8e21eae311b64a005056801da1,70.387182,0.022767,3.486736e-13,0.957030,3.668211,0.000988,0.009955,0.027645,0.832915,0.261169,0.789720,0.712317,9247,2024-03-25,1.3,0.540709
1,03d6a454c3de,bc7b5e8e21eae311b64a005056801da1,69.032380,-0.000382,5.448425e-14,0.990786,4.273642,0.000999,0.023988,0.016896,0.814612,0.636964,0.782982,0.680363,6625,2024-03-25,1.3,0.540709
2,041762988fc6,bc7b5e8e21eae311b64a005056801da1,29.337754,-0.027698,8.433487e-02,1.000000,2.514609,0.003375,0.036890,0.021804,0.704879,0.751915,0.713770,0.583673,9133,2024-03-25,1.3,0.540709
3,042be327b7d9,bc7b5e8e21eae311b64a005056801da1,70.467524,0.021816,4.002897e-11,0.966150,3.559106,0.000927,0.009961,0.025747,0.834225,0.242820,0.827655,0.670118,9352,2024-03-25,1.3,0.540709
4,0451bd23ae22,bc7b5e8e21eae311b64a005056801da1,36.886380,0.016789,2.414249e-02,1.000000,3.687978,0.002981,0.040492,0.039129,0.701185,0.513246,0.577762,0.710192,5958,2024-03-25,1.3,0.540709
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106642,c9e287faf961,9c8063d82400e4119e54005056801da1,8.415374,-0.268215,4.741020e-13,0.978466,0.887805,0.023633,0.060258,0.011605,0.777819,0.877293,0.584106,0.798387,2637,2024-03-25,1.3,0.668942
106643,c9fb774e480b,9c8063d82400e4119e54005056801da1,21.715597,-0.040910,5.153232e-15,0.983474,1.709024,0.004150,0.031590,0.012757,0.891011,0.659936,0.755249,0.904918,2582,2024-03-25,1.3,0.668942
106644,d3dd4d74bc29,9c8063d82400e4119e54005056801da1,6.453172,-0.228860,7.228266e-16,0.987656,0.798026,0.028779,0.063965,0.017162,0.763622,0.824429,0.513929,0.859232,2629,2024-03-25,1.3,0.668942
106645,d5c96706d9d6,9c8063d82400e4119e54005056801da1,8.281215,-0.198515,2.635557e-14,0.976633,0.892442,0.019438,0.050531,0.014647,0.784525,0.841281,0.528275,0.869027,2687,2024-03-25,1.3,0.668942
106646,e3174b02c189,9c8063d82400e4119e54005056801da1,100.000000,-0.117890,6.006335e-20,0.966532,8.936638,0.001472,0.019913,0.004322,0.904885,0.966267,0.673239,0.943609,2751,2024-03-25,1.3,0.668942

In [19]:
##### skill_optimal_threshold,student_mean_accuracy,
df['student_mean_accuracy']=0.5
# df['version']=1.2
df

,question_id,skill_or_subskill_id,discriminability,difficulty,guessing,inattention,discriminability_error,difficulty_error,guessing_error,inattention_error,auc_roc,optimal_threshold,tpr,tnr,sample_size,date_created,version,skill_optimal_threshold,student_mean_accuracy
0,01ca3ac546e3,bc7b5e8e21eae311b64a005056801da1,70.387182,0.022767,3.486736e-13,0.957030,3.668211,0.000988,0.009955,0.027645,0.832915,0.261169,0.789720,0.712317,9247,2024-03-25,1.3,0.540709,0.5
1,03d6a454c3de,bc7b5e8e21eae311b64a005056801da1,69.032380,-0.000382,5.448425e-14,0.990786,4.273642,0.000999,0.023988,0.016896,0.814612,0.636964,0.782982,0.680363,6625,2024-03-25,1.3,0.540709,0.5
2,041762988fc6,bc7b5e8e21eae311b64a005056801da1,29.337754,-0.027698,8.433487e-02,1.000000,2.514609,0.003375,0.036890,0.021804,0.704879,0.751915,0.713770,0.583673,9133,2024-03-25,1.3,0.540709,0.5
3,042be327b7d9,bc7b5e8e21eae311b64a005056801da1,70.467524,0.021816,4.002897e-11,0.966150,3.559106,0.000927,0.009961,0.025747,0.834225,0.242820,0.827655,0.670118,9352,2024-03-25,1.3,0.540709,0.5
4,0451bd23ae22,bc7b5e8e21eae311b64a005056801da1,36.886380,0.016789,2.414249e-02,1.000000,3.687978,0.002981,0.040492,0.039129,0.701185,0.513246,0.577762,0.710192,5958,2024-03-25,1.3,0.540709,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106642,c9e287faf961,9c8063d82400e4119e54005056801da1,8.415374,-0.268215,4.741020e-13,0.978466,0.887805,0.023633,0.060258,0.011605,0.777819,0.877293,0.584106,0.798387,2637,2024-03-25,1.3,0.668942,0.5
106643,c9fb774e480b,9c8063d82400e4119e54005056801da1,21.715597,-0.040910,5.153232e-15,0.983474,1.709024,0.004150,0.031590,0.012757,0.891011,0.659936,0.755249,0.904918,2582,2024-03-25,1.3,0.668942,0.5
106644,d3dd4d74bc29,9c8063d82400e4119e54005056801da1,6.453172,-0.228860,7.228266e-16,0.987656,0.798026,0.028779,0.063965,0.017162,0.763622,0.824429,0.513929,0.859232,2629,2024-03-25,1.3,0.668942,0.5
106645,d5c96706d9d6,9c8063d82400e4119e54005056801da1,8.281215,-0.198515,2.635557e-14,0.976633,0.892442,0.019438,0.050531,0.014647,0.784525,0.841281,0.528275,0.869027,2687,2024-03-25,1.3,0.668942,0.5
106646,e3174b02c189,9c8063d82400e4119e54005056801da1,100.000000,-0.117890,6.006335e-20,0.966532,8.936638,0.001472,0.019913,0.004322,0.904885,0.966267,0.673239,0.943609,2751,2024-03-25,1.3,0.668942,0.5

In [21]:
df.to_csv('ItemParameterEstimates20240325.csv',index=False)