In [120]:
file= 'data__0_2_6.snappy.parquet'
# folder = 'feature_engineered_train_parquets/'
folder = 'feature_engineered_train_parquets_newIP_moreFeatures/'
jsoncolumns = 'feature_engineered_column_names.json'
# Load column names
import json; 
feature_engineered_column_names = json.load(open(folder + jsoncolumns))

import pandas as pd
fdf = pd.read_parquet(folder+file)
fdf.columns = feature_engineered_column_names

pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', None)  # Set width to max available width
pd.set_option('display.max_colwidth', None)  # Show full content of each column
pd.set_option('display.expand_frame_repr', False)  # Don't wrap to multiple lines

# df
import numpy as np
occurred_columns = [f'OCCURREDAT_DIFF_{i}' for i in range(1, 10)]
correctness_columns = [f'CORRECTNESS_LAG_{i}' for i in range(1, 10)]

fdf

       STUDENTID     SKILL                            QUESTIONID  CORRECTNESS  ANSWERPOSITIONINSESSION EVENT_RANK                      QUESTIONID_LAG_1                      QUESTIONID_LAG_2                      QUESTIONID_LAG_3                      QUESTIONID_LAG_4                      QUESTIONID_LAG_5                      QUESTIONID_LAG_6                      QUESTIONID_LAG_7                      QUESTIONID_LAG_8                      QUESTIONID_LAG_9  CORRECTNESS_LAG_1  CORRECTNESS_LAG_2  CORRECTNESS_LAG_3  CORRECTNESS_LAG_4  CORRECTNESS_LAG_5  CORRECTNESS_LAG_6  CORRECTNESS_LAG_7  CORRECTNESS_LAG_8  CORRECTNESS_LAG_9  DURATIONSECONDS_LAG_1  DURATIONSECONDS_LAG_2  DURATIONSECONDS_LAG_3  DURATIONSECONDS_LAG_4  DURATIONSECONDS_LAG_5  DURATIONSECONDS_LAG_6  DURATIONSECONDS_LAG_7  DURATIONSECONDS_LAG_8  DURATIONSECONDS_LAG_9  OCCURREDAT_DIFF_1  OCCURREDAT_DIFF_2  OCCURREDAT_DIFF_3  OCCURREDAT_DIFF_4  OCCURREDAT_DIFF_5  OCCURREDAT_DIFF_6  OCCURREDAT_DIFF_7  OCCURREDAT_DIFF_8  OCCURREDAT_DIFF_9  LOG_OCCURREDAT_DIFF_1  LOG_OCCURREDAT_DIFF_2  LOG_OCCURREDAT_DIFF_3  LOG_OCCURREDAT_DIFF_4  LOG_OCCURREDAT_DIFF_5  LOG_OCCURREDAT_DIFF_6  LOG_OCCURREDAT_DIFF_7  LOG_OCCURREDAT_DIFF_8  LOG_OCCURREDAT_DIFF_9  LOG_DURATIONSECONDS_LAG_1  LOG_DURATIONSECONDS_LAG_2  LOG_DURATIONSECONDS_LAG_3  LOG_DURATIONSECONDS_LAG_4  LOG_DURATIONSECONDS_LAG_5  LOG_DURATIONSECONDS_LAG_6  LOG_DURATIONSECONDS_LAG_7  LOG_DURATIONSECONDS_LAG_8  LOG_DURATIONSECONDS_LAG_9  discriminability  difficulty      guessing  inattention  discriminability_error  difficulty_error  guessing_error  inattention_error   auc_roc  optimal_threshold       tpr       tnr  skill_optimal_threshold  student_mean_accuracy  discriminability_LAG_1  difficulty_LAG_1  guessing_LAG_1  inattention_LAG_1  discriminability_error_LAG_1  difficulty_error_LAG_1  guessing_error_LAG_1  inattention_error_LAG_1  auc_roc_LAG_1  optimal_threshold_LAG_1  tpr_LAG_1  tnr_LAG_1  student_mean_accuracy_LAG_1  discriminability_LAG_2  difficulty_LAG_2  guessing_LAG_2  inattention_LAG_2  discriminability_error_LAG_2  difficulty_error_LAG_2  guessing_error_LAG_2  inattention_error_LAG_2  auc_roc_LAG_2  optimal_threshold_LAG_2  tpr_LAG_2  tnr_LAG_2  student_mean_accuracy_LAG_2  discriminability_LAG_3  difficulty_LAG_3  guessing_LAG_3  inattention_LAG_3  discriminability_error_LAG_3  difficulty_error_LAG_3  guessing_error_LAG_3  inattention_error_LAG_3  auc_roc_LAG_3  optimal_threshold_LAG_3  tpr_LAG_3  tnr_LAG_3  student_mean_accuracy_LAG_3  discriminability_LAG_4  difficulty_LAG_4  guessing_LAG_4  inattention_LAG_4  discriminability_error_LAG_4  difficulty_error_LAG_4  guessing_error_LAG_4  inattention_error_LAG_4  auc_roc_LAG_4  optimal_threshold_LAG_4  tpr_LAG_4  tnr_LAG_4  student_mean_accuracy_LAG_4  discriminability_LAG_5  difficulty_LAG_5  guessing_LAG_5  inattention_LAG_5  discriminability_error_LAG_5  difficulty_error_LAG_5  guessing_error_LAG_5  inattention_error_LAG_5  auc_roc_LAG_5  optimal_threshold_LAG_5  tpr_LAG_5  tnr_LAG_5  student_mean_accuracy_LAG_5  discriminability_LAG_6  difficulty_LAG_6  guessing_LAG_6  inattention_LAG_6  discriminability_error_LAG_6  difficulty_error_LAG_6  guessing_error_LAG_6  inattention_error_LAG_6  auc_roc_LAG_6  optimal_threshold_LAG_6  tpr_LAG_6  tnr_LAG_6  student_mean_accuracy_LAG_6  discriminability_LAG_7  difficulty_LAG_7  guessing_LAG_7  inattention_LAG_7  discriminability_error_LAG_7  difficulty_error_LAG_7  guessing_error_LAG_7  inattention_error_LAG_7  auc_roc_LAG_7  optimal_threshold_LAG_7  tpr_LAG_7  tnr_LAG_7  student_mean_accuracy_LAG_7  discriminability_LAG_8  difficulty_LAG_8  guessing_LAG_8  inattention_LAG_8  discriminability_error_LAG_8  difficulty_error_LAG_8  guessing_error_LAG_8  inattention_error_LAG_8  auc_roc_LAG_8  optimal_threshold_LAG_8  tpr_LAG_8  tnr_LAG_8  student_mean_accuracy_LAG_8  discriminability_LAG_9  difficulty_LAG_9  guessing_LAG_9  inattention_LAG_9  discriminability_error_LAG_9  difficulty_error_LAG_9  guessing_error_LAG_9  inattention_error_LAG_9  auc_roc_LAG_9  optimal_threshold_LAG_9  tpr_LAG_9  tnr_LAG_9  student_mean_accuracy_LAG_9  LOG_sample_size  LOG_sample_size_LAG_1  LOG_sample_size_LAG_2  LOG_sample_size_LAG_3  LOG_sample_size_LAG_4  LOG_sample_size_LAG_5  LOG_sample_size_LAG_6  LOG_sample_size_LAG_7  LOG_sample_size_LAG_8  LOG_sample_size_LAG_9  difficulty_spread  optimal_threshold_spread  student_mean_accuracy_spread  tnr_spread  tpr_spread  mean_auc_roc  mean_discriminability  mean_discriminability_error  mean_difficulty_error  mean_guessing_error  mean_inattention_error  num_responses
0       36617855  pkjpfxrt  aa7e9906-76fd-4914-844a-2f27e8185553          0.0                      0.0          2  a2926c00-6e25-4b78-919b-7e3ed66bccef                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                1.0                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN          20.605592                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN               3.025562                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN         61.216550   -0.022265  1.709568e-01     0.997268               11.075314          0.004410        0.090084           0.027130  0.815265           0.758498  0.679191  0.805310                      NaN               0.753813              100.000000          0.003660    3.310931e-01           1.000000                     21.350563                0.002275              0.033704                 0.032616       0.796723                 0.588902   0.641953   0.876081                     0.614444                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN         6.822197               6.802395                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN           0.000000                  0.000000                      0.000000    0.000000    0.000000      0.796723             100.000000                    21.350563               0.002275             0.033704                0.032616              1
1       36617855  pkjpfxrt  a2926c00-6e25-4b78-919b-7e3ed66bccef          1.0                      0.0          1                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN        100.000000    0.003660  3.310931e-01     1.000000               21.350563          0.002275        0.033704           0.032616  0.796723           0.588902  0.641953  0.876081                      NaN               0.614444                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN                     NaN               NaN             NaN                NaN                           NaN                     NaN                   NaN                      NaN            NaN                      NaN        NaN        NaN                          NaN         6.802395                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                NaN                       NaN                           NaN         NaN         NaN           NaN                    NaN                          NaN                    NaN                  NaN                     NaN              0
2       36617855  utusgzma  f7914999-6264-4c7a-9d0c-39f2825ec2ac          1.0                      9.0         10  f1619b4d-4439-4134-8b4b-d888a7c5dc81  c11f8eac-8cc8-456e-8a61-403df968a070  b0f403f3-9185-42de-b5df-cc1711f4a330  a3a92c80-43d6-4560-816d-b6538bddf0df  9d253c11-7057-470c-8f09-f0d2821e963a  99d69c1e-0742-4f19-8796-7c63d56ac6ae  993dda04-c1b0-4cc8-bd35-e670b9a9f35d  9075f9ad-c505-43e5-b4bc-87c8eded9c94  8be1ec2c-833f-419e-8d74-f6ac07b6b2ee                1.0                1.0                1.0                1.0                1.0                1.0                1.0                1.0                1.0                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN           0.002854           0.005065           0.001666           0.001436           0.001487           0.001662           0.002109           0.001720           0.001939              -5.858975              -5.285346              -6.397597              -6.545623              -6.511032              -6.399767              -6.161726               -6.36527               -6.24564                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN                        NaN         45.187145         NaN  1.351850e-13     0.994499                6.145653          0.005280        0.103308           0.016590  0.833621           0.724428  0.666667  0.835648                      NaN               0.736746              100.000000               NaN    2.203398e-01           1.000000                     13.988289                0.001388              0.024242                 0.018521       0.840477                 0.516506   0.707926   0.927374                     0.562615               72.454959               NaN    2.087083e-01           0.994971                      8.688671                0.003072              0.063951                 0.010561       0.868111                 0.900581   0.694572   0.873171                     0.881776               77.909214               NaN    1.313609e-02           1.000000                      6.510197                0.002141              0.059815                 0.008042       0.907594                 0.919023   0.756098   0.884393                     0.906688               73.922901               NaN    2.842315e-03           1.000000                      6.337311                0.002108              0.054348                 0.009616       0.913927                 0.902790   0.741414   0.918552                     0.870457              100.000000               NaN        0.055152           1.000000                      8.559204                0.001568              0.048985                 0.006756       0.947401                 0.899783   0.861742   0.884892                     0.919327              100.000000               NaN        0.268880           1.000000                     15.537147                0.001550              0.027102                 0.020475       0.819789                 0.513428   0.678419   0.885370                     0.585366               69.233623               NaN        0.035951           0.998278                      6.762493                0.002624              0.064926                 0.010467       0.883178                 0.864644   0.784121   0.806306                     0.872852                   100.0               NaN        0.022799           1.000000                      7.698641                0.001429              0.046601                 0.006578       0.954986                 0.928092   0.836426   0.942149                     0.923223                   100.0               NaN        0.089887           0.997923                      9.429205                0.001727              0.050782                 0.006483       0.936786                   0.9578   0.822644   0.901235                     0.939732         7.403061               7.400621               7.458186               7.525101               7.441907               7.451822               7.377134               7.465083               7.362645               7.203406                NaN                  0.444372                      0.377118    0.135842    0.183324      0.896917              88.168966                     9.279017               0.001956             0.048972                0.010833              9

0          100
1         None
2          100
3          100
4          100
          ...
205845       0
205846     100
205847     100
205848     100
205849    None
Name: CORRECTNESS_LAG_1, Length: 205850, dtype: object

In [95]:
duration_columns = ['DURATIONSECONDS'] + [f'DURATIONSECONDS_LAG_{i}' for i in range(1, 10)]

fdf[occurred_columns]

        OCCURREDAT_DIFF_1  OCCURREDAT_DIFF_2  OCCURREDAT_DIFF_3  OCCURREDAT_DIFF_4  OCCURREDAT_DIFF_5  OCCURREDAT_DIFF_6  OCCURREDAT_DIFF_7  OCCURREDAT_DIFF_8  OCCURREDAT_DIFF_9
0               20.605592                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
1                     NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
2                0.002854           0.005065           0.001666           0.001436           0.001487           0.001662           0.002109           0.001720           0.001939
3                0.005065           0.001666           0.001436           0.001487           0.001662           0.002109           0.001720           0.001939                NaN
4                0.001666           0.001436           0.001487           0.001662           0.002109           0.001720           0.001939                NaN                NaN
...                   ...                ...                ...                ...                ...                ...                ...                ...                ...
205845           0.003046           0.003342           0.005469           0.002241                NaN                NaN                NaN                NaN                NaN
205846           0.003342           0.005469           0.002241                NaN                NaN                NaN                NaN                NaN                NaN
205847           0.005469           0.002241                NaN                NaN                NaN                NaN                NaN                NaN                NaN
205848           0.002241                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
205849                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN

[205850 rows x 9 columns]

In [96]:
# np.nanmax(fdf[occurred_columns])
# fdf[fdf.OCCURREDAT_DIFF_1==
# for i in fdf.columns:
#     print(i)
# fdf[fdf.STUDENTID==41269220][occurred_columns]

In [97]:
1/3600

0.0002777777777777778

In [98]:

# for i in range(1,5):
#     print((df[df.STUDENTID==41269220].OCCURREDAT.loc[i-1]-df[df.STUDENTID==41269220].OCCURREDAT.loc[i]).total_seconds() / 3600)

In [99]:
import pandas as pd
df = pd.read_parquet('StudentProficiencyData_ELA_09252024/'+file)

# Load column names
with open('column_names.txt', 'r') as f:
    column_names = f.read().splitlines()

df.columns = column_names

pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', None)  # Set width to max available width
pd.set_option('display.max_colwidth', None)  # Show full content of each column
pd.set_option('display.expand_frame_repr', False)  # Don't wrap to multiple lines

# (df.OCCURREDAT.iloc[0]-df.OCCURREDAT.iloc[1]).total_seconds()/3600
df

       STUDENTID     SKILL                            QUESTIONID                       OCCURREDAT CORRECTNESS  DURATIONSECONDS  ANSWERPOSITIONINSESSION EVENT_RANK                      QUESTIONID_LAG_1                      QUESTIONID_LAG_2                      QUESTIONID_LAG_3                      QUESTIONID_LAG_4                      QUESTIONID_LAG_5                      QUESTIONID_LAG_6                      QUESTIONID_LAG_7                      QUESTIONID_LAG_8                      QUESTIONID_LAG_9                 OCCURREDAT_LAG_1                 OCCURREDAT_LAG_2                 OCCURREDAT_LAG_3                 OCCURREDAT_LAG_4                 OCCURREDAT_LAG_5                 OCCURREDAT_LAG_6                 OCCURREDAT_LAG_7                 OCCURREDAT_LAG_8                 OCCURREDAT_LAG_9 CORRECTNESS_LAG_1 CORRECTNESS_LAG_2 CORRECTNESS_LAG_3 CORRECTNESS_LAG_4 CORRECTNESS_LAG_5 CORRECTNESS_LAG_6 CORRECTNESS_LAG_7 CORRECTNESS_LAG_8 CORRECTNESS_LAG_9  DURATIONSECONDS_LAG_1  DURATIONSECONDS_LAG_2  DURATIONSECONDS_LAG_3  DURATIONSECONDS_LAG_4  DURATIONSECONDS_LAG_5  DURATIONSECONDS_LAG_6  DURATIONSECONDS_LAG_7  DURATIONSECONDS_LAG_8  DURATIONSECONDS_LAG_9
0       36617855  pkjpfxrt  aa7e9906-76fd-4914-844a-2f27e8185553 2024-06-13 13:13:34.062000+00:00           0              NaN                      0.0          2  a2926c00-6e25-4b78-919b-7e3ed66bccef                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None 2024-06-12 16:37:13.931000+00:00                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT               100              None              None              None              None              None              None              None              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN
1       36617855  pkjpfxrt  a2926c00-6e25-4b78-919b-7e3ed66bccef 2024-06-12 16:37:13.931000+00:00         100              NaN                      0.0          1                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT              None              None              None              None              None              None              None              None              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN
2       36617855  utusgzma  f7914999-6264-4c7a-9d0c-39f2825ec2ac 2024-06-12 16:36:49.217000+00:00         100              NaN                      9.0         10  f1619b4d-4439-4134-8b4b-d888a7c5dc81  c11f8eac-8cc8-456e-8a61-403df968a070  b0f403f3-9185-42de-b5df-cc1711f4a330  a3a92c80-43d6-4560-816d-b6538bddf0df  9d253c11-7057-470c-8f09-f0d2821e963a  99d69c1e-0742-4f19-8796-7c63d56ac6ae  993dda04-c1b0-4cc8-bd35-e670b9a9f35d  9075f9ad-c505-43e5-b4bc-87c8eded9c94  8be1ec2c-833f-419e-8d74-f6ac07b6b2ee 2024-06-12 16:36:38.942000+00:00 2024-06-12 16:36:20.707000+00:00 2024-06-12 16:36:14.711000+00:00 2024-06-12 16:36:09.540000+00:00 2024-06-12 16:36:04.187000+00:00 2024-06-12 16:35:58.204000+00:00 2024-06-12 16:35:50.613000+00:00 2024-06-12 16:35:44.420000+00:00 2024-06-12 16:35:37.440000+00:00               100               100               100               100               100               100               100               100               100                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN
3       36617855  utusgzma  f1619b4d-4439-4134-8b4b-d888a7c5dc81 2024-06-12 16:36:38.942000+00:00         100              NaN                      8.0          9  c11f8eac-8cc8-456e-8a61-403df968a070  b0f403f3-9185-42de-b5df-cc1711f4a330  a3a92c80-43d6-4560-816d-b6538bddf0df  9d253c11-7057-470c-8f09-f0d2821e963a  99d69c1e-0742-4f19-8796-7c63d56ac6ae  993dda04-c1b0-4cc8-bd35-e670b9a9f35d  9075f9ad-c505-43e5-b4bc-87c8eded9c94  8be1ec2c-833f-419e-8d74-f6ac07b6b2ee                                  None 2024-06-12 16:36:20.707000+00:00 2024-06-12 16:36:14.711000+00:00 2024-06-12 16:36:09.540000+00:00 2024-06-12 16:36:04.187000+00:00 2024-06-12 16:35:58.204000+00:00 2024-06-12 16:35:50.613000+00:00 2024-06-12 16:35:44.420000+00:00 2024-06-12 16:35:37.440000+00:00                              NaT               100               100               100               100               100               100               100               100              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN
4       36617855  utusgzma  c11f8eac-8cc8-456e-8a61-403df968a070 2024-06-12 16:36:20.707000+00:00         100              NaN                      7.0          8  b0f403f3-9185-42de-b5df-cc1711f4a330  a3a92c80-43d6-4560-816d-b6538bddf0df  9d253c11-7057-470c-8f09-f0d2821e963a  99d69c1e-0742-4f19-8796-7c63d56ac6ae  993dda04-c1b0-4cc8-bd35-e670b9a9f35d  9075f9ad-c505-43e5-b4bc-87c8eded9c94  8be1ec2c-833f-419e-8d74-f6ac07b6b2ee                                  None                                  None 2024-06-12 16:36:14.711000+00:00 2024-06-12 16:36:09.540000+00:00 2024-06-12 16:36:04.187000+00:00 2024-06-12 16:35:58.204000+00:00 2024-06-12 16:35:50.613000+00:00 2024-06-12 16:35:44.420000+00:00 2024-06-12 16:35:37.440000+00:00                              NaT                              NaT               100               100               100               100               100               100               100              None              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN
...          ...       ...                                   ...                              ...         ...              ...                      ...        ...                                   ...                                   ...                                   ...                                   ...                                   ...                                   ...                                   ...                                   ...                                   ...                              ...                              ...                              ...                              ...                              ...                              ...                              ...                              ...                              ...               ...               ...               ...               ...               ...               ...               ...               ...               ...                    ...                    ...                    ...                    ...                    ...                    ...                    ...                    ...                    ...
258043  26645986  kbuerkhf  84c04afb-86bb-4c30-ac90-801cf5b465b8 2024-09-16 20:40:48.649000+00:00           0             20.0                      0.0          1                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT              None              None              None              None              None              None              None              None              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN
258044  26645986  kjhgvfce  e8e06f01-4932-457d-8059-779c3dcc4ce4 2024-09-16 20:24:29.585000+00:00         100              8.0                      9.0         10  e7ac35b9-7fe5-44a1-89a2-ef560fb296a3  e75fe696-f8a6-4994-97a2-071ac422cc83  d7f5752f-7df6-4ab6-80fc-37a06bcd705b  d707f485-ed1b-4660-863b-c89a53d8093e  bc01a61d-f114-46d9-afa5-4f440af6ead4  833cbc50-f160-48d0-b280-0a41149f0296  81bc4469-101e-4a30-9371-7a52a2770593  7f7f27e2-c4ee-485b-89ef-6030be6ef03b  715e87ff-9315-44bd-9cf1-a5cf6e011dda 2024-09-16 20:24:16.684000+00:00 2024-09-16 20:24:09.983000+00:00 2024-09-16 20:24:03.078000+00:00 2024-09-16 20:23:56.763000+00:00 2024-09-16 20:23:46.304000+00:00 2024-09-16 20:23:34.265000+00:00 2024-09-16 20:23:24.377000+00:00 2024-09-16 20:23:12.806000+00:00 2024-09-16 20:23:00.228000+00:00                 0               100               100               100                 0               100               100               100               100                    6.0                    5.0                    5.0                    6.0                    9.0                    9.0                   10.0                   11.0                    9.0
258045  26645986  kjhgvfce  e7ac35b9-7fe5-44a1-89a2-ef560fb296a3 2024-09-16 20:24:16.684000+00:00           0              6.0                      8.0          9  e75fe696-f8a6-4994-97a2-071ac422cc83  d7f5752f-7df6-4ab6-80fc-37a06bcd705b  d707f485-ed1b-4660-863b-c89a53d8093e  bc01a61d-f114-46d9-afa5-4f440af6ead4  833cbc50-f160-48d0-b280-0a41149f0296  81bc4469-101e-4a30-9371-7a52a2770593  7f7f27e2-c4ee-485b-89ef-6030be6ef03b  715e87ff-9315-44bd-9cf1-a5cf6e011dda                                  None 2024-09-16 20:24:09.983000+00:00 2024-09-16 20:24:03.078000+00:00 2024-09-16 20:23:56.763000+00:00 2024-09-16 20:23:46.304000+00:00 2024-09-16 20:23:34.265000+00:00 2024-09-16 20:23:24.377000+00:00 2024-09-16 20:23:12.806000+00:00 2024-09-16 20:23:00.228000+00:00                              NaT               100               100               100                 0               100               100               100               100              None                    5.0                    5.0                    6.0                    9.0                    9.0                   10.0                   11.0                    9.0                    NaN
258046  26645986  kjhgvfce  e75fe696-f8a6-4994-97a2-071ac422cc83 2024-09-16 20:24:09.983000+00:00         100              5.0                      7.0          8  d7f5752f-7df6-4ab6-80fc-37a06bcd705b  d707f485-ed1b-4660-863b-c89a53d8093e  bc01a61d-f114-46d9-afa5-4f440af6ead4  833cbc50-f160-48d0-b280-0a41149f0296  81bc4469-101e-4a30-9371-7a52a2770593  7f7f27e2-c4ee-485b-89ef-6030be6ef03b  715e87ff-9315-44bd-9cf1-a5cf6e011dda                                  None                                  None 2024-09-16 20:24:03.078000+00:00 2024-09-16 20:23:56.763000+00:00 2024-09-16 20:23:46.304000+00:00 2024-09-16 20:23:34.265000+00:00 2024-09-16 20:23:24.377000+00:00 2024-09-16 20:23:12.806000+00:00 2024-09-16 20:23:00.228000+00:00                              NaT                              NaT               100               100                 0               100               100               100               100              None              None                    5.0                    6.0                    9.0                    9.0                   10.0                   11.0                    9.0                    NaN                    NaN
258047  26645986  kjhgvfce  d7f5752f-7df6-4ab6-80fc-37a06bcd705b 2024-09-16 20:24:03.078000+00:00         100              5.0                      6.0          7  d707f485-ed1b-4660-863b-c89a53d8093e  bc01a61d-f114-46d9-afa5-4f440af6ead4  833cbc50-f160-48d0-b280-0a41149f0296  81bc4469-101e-4a30-9371-7a52a2770593  7f7f27e2-c4ee-485b-89ef-6030be6ef03b  715e87ff-9315-44bd-9cf1-a5cf6e011dda                                  None                                  None                                  None 2024-09-16 20:23:56.763000+00:00 2024-09-16 20:23:46.304000+00:00 2024-09-16 20:23:34.265000+00:00 2024-09-16 20:23:24.377000+00:00 2024-09-16 20:23:12.806000+00:00 2024-09-16 20:23:00.228000+00:00                              NaT                              NaT                              NaT               100                 0               100               100               100               100              None              None              None                    6.0                    9.0                    9.0                   10.0                   11.0                    9.0                    NaN                    NaN                    NaN

[258048 rows x 44 columns]

In [100]:
occurred_columns = ['OCCURREDAT'] + [f'OCCURREDAT_LAG_{i}' for i in range(1, 10)]
for i in range(1, len(occurred_columns)):
    diff_col = f'OCCURREDAT_DIFF_{i}'
    df[diff_col] = (df[occurred_columns[i-1]] - df[occurred_columns[i]]).dt.total_seconds() / 3600
df

       STUDENTID     SKILL                            QUESTIONID                       OCCURREDAT CORRECTNESS  DURATIONSECONDS  ANSWERPOSITIONINSESSION EVENT_RANK                      QUESTIONID_LAG_1                      QUESTIONID_LAG_2                      QUESTIONID_LAG_3                      QUESTIONID_LAG_4                      QUESTIONID_LAG_5                      QUESTIONID_LAG_6                      QUESTIONID_LAG_7                      QUESTIONID_LAG_8                      QUESTIONID_LAG_9                 OCCURREDAT_LAG_1                 OCCURREDAT_LAG_2                 OCCURREDAT_LAG_3                 OCCURREDAT_LAG_4                 OCCURREDAT_LAG_5                 OCCURREDAT_LAG_6                 OCCURREDAT_LAG_7                 OCCURREDAT_LAG_8                 OCCURREDAT_LAG_9 CORRECTNESS_LAG_1 CORRECTNESS_LAG_2 CORRECTNESS_LAG_3 CORRECTNESS_LAG_4 CORRECTNESS_LAG_5 CORRECTNESS_LAG_6 CORRECTNESS_LAG_7 CORRECTNESS_LAG_8 CORRECTNESS_LAG_9  DURATIONSECONDS_LAG_1  DURATIONSECONDS_LAG_2  DURATIONSECONDS_LAG_3  DURATIONSECONDS_LAG_4  DURATIONSECONDS_LAG_5  DURATIONSECONDS_LAG_6  DURATIONSECONDS_LAG_7  DURATIONSECONDS_LAG_8  DURATIONSECONDS_LAG_9  OCCURREDAT_DIFF_1  OCCURREDAT_DIFF_2  OCCURREDAT_DIFF_3  OCCURREDAT_DIFF_4  OCCURREDAT_DIFF_5  OCCURREDAT_DIFF_6  OCCURREDAT_DIFF_7  OCCURREDAT_DIFF_8  OCCURREDAT_DIFF_9
0       36617855  pkjpfxrt  aa7e9906-76fd-4914-844a-2f27e8185553 2024-06-13 13:13:34.062000+00:00           0              NaN                      0.0          2  a2926c00-6e25-4b78-919b-7e3ed66bccef                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None 2024-06-12 16:37:13.931000+00:00                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT               100              None              None              None              None              None              None              None              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN          20.605592                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
1       36617855  pkjpfxrt  a2926c00-6e25-4b78-919b-7e3ed66bccef 2024-06-12 16:37:13.931000+00:00         100              NaN                      0.0          1                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT              None              None              None              None              None              None              None              None              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
2       36617855  utusgzma  f7914999-6264-4c7a-9d0c-39f2825ec2ac 2024-06-12 16:36:49.217000+00:00         100              NaN                      9.0         10  f1619b4d-4439-4134-8b4b-d888a7c5dc81  c11f8eac-8cc8-456e-8a61-403df968a070  b0f403f3-9185-42de-b5df-cc1711f4a330  a3a92c80-43d6-4560-816d-b6538bddf0df  9d253c11-7057-470c-8f09-f0d2821e963a  99d69c1e-0742-4f19-8796-7c63d56ac6ae  993dda04-c1b0-4cc8-bd35-e670b9a9f35d  9075f9ad-c505-43e5-b4bc-87c8eded9c94  8be1ec2c-833f-419e-8d74-f6ac07b6b2ee 2024-06-12 16:36:38.942000+00:00 2024-06-12 16:36:20.707000+00:00 2024-06-12 16:36:14.711000+00:00 2024-06-12 16:36:09.540000+00:00 2024-06-12 16:36:04.187000+00:00 2024-06-12 16:35:58.204000+00:00 2024-06-12 16:35:50.613000+00:00 2024-06-12 16:35:44.420000+00:00 2024-06-12 16:35:37.440000+00:00               100               100               100               100               100               100               100               100               100                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN           0.002854           0.005065           0.001666           0.001436           0.001487           0.001662           0.002109           0.001720           0.001939
3       36617855  utusgzma  f1619b4d-4439-4134-8b4b-d888a7c5dc81 2024-06-12 16:36:38.942000+00:00         100              NaN                      8.0          9  c11f8eac-8cc8-456e-8a61-403df968a070  b0f403f3-9185-42de-b5df-cc1711f4a330  a3a92c80-43d6-4560-816d-b6538bddf0df  9d253c11-7057-470c-8f09-f0d2821e963a  99d69c1e-0742-4f19-8796-7c63d56ac6ae  993dda04-c1b0-4cc8-bd35-e670b9a9f35d  9075f9ad-c505-43e5-b4bc-87c8eded9c94  8be1ec2c-833f-419e-8d74-f6ac07b6b2ee                                  None 2024-06-12 16:36:20.707000+00:00 2024-06-12 16:36:14.711000+00:00 2024-06-12 16:36:09.540000+00:00 2024-06-12 16:36:04.187000+00:00 2024-06-12 16:35:58.204000+00:00 2024-06-12 16:35:50.613000+00:00 2024-06-12 16:35:44.420000+00:00 2024-06-12 16:35:37.440000+00:00                              NaT               100               100               100               100               100               100               100               100              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN           0.005065           0.001666           0.001436           0.001487           0.001662           0.002109           0.001720           0.001939                NaN
4       36617855  utusgzma  c11f8eac-8cc8-456e-8a61-403df968a070 2024-06-12 16:36:20.707000+00:00         100              NaN                      7.0          8  b0f403f3-9185-42de-b5df-cc1711f4a330  a3a92c80-43d6-4560-816d-b6538bddf0df  9d253c11-7057-470c-8f09-f0d2821e963a  99d69c1e-0742-4f19-8796-7c63d56ac6ae  993dda04-c1b0-4cc8-bd35-e670b9a9f35d  9075f9ad-c505-43e5-b4bc-87c8eded9c94  8be1ec2c-833f-419e-8d74-f6ac07b6b2ee                                  None                                  None 2024-06-12 16:36:14.711000+00:00 2024-06-12 16:36:09.540000+00:00 2024-06-12 16:36:04.187000+00:00 2024-06-12 16:35:58.204000+00:00 2024-06-12 16:35:50.613000+00:00 2024-06-12 16:35:44.420000+00:00 2024-06-12 16:35:37.440000+00:00                              NaT                              NaT               100               100               100               100               100               100               100              None              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN           0.001666           0.001436           0.001487           0.001662           0.002109           0.001720           0.001939                NaN                NaN
...          ...       ...                                   ...                              ...         ...              ...                      ...        ...                                   ...                                   ...                                   ...                                   ...                                   ...                                   ...                                   ...                                   ...                                   ...                              ...                              ...                              ...                              ...                              ...                              ...                              ...                              ...                              ...               ...               ...               ...               ...               ...               ...               ...               ...               ...                    ...                    ...                    ...                    ...                    ...                    ...                    ...                    ...                    ...                ...                ...                ...                ...                ...                ...                ...                ...                ...
258043  26645986  kbuerkhf  84c04afb-86bb-4c30-ac90-801cf5b465b8 2024-09-16 20:40:48.649000+00:00           0             20.0                      0.0          1                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                                  None                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT                              NaT              None              None              None              None              None              None              None              None              None                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                    NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN                NaN
258044  26645986  kjhgvfce  e8e06f01-4932-457d-8059-779c3dcc4ce4 2024-09-16 20:24:29.585000+00:00         100              8.0                      9.0         10  e7ac35b9-7fe5-44a1-89a2-ef560fb296a3  e75fe696-f8a6-4994-97a2-071ac422cc83  d7f5752f-7df6-4ab6-80fc-37a06bcd705b  d707f485-ed1b-4660-863b-c89a53d8093e  bc01a61d-f114-46d9-afa5-4f440af6ead4  833cbc50-f160-48d0-b280-0a41149f0296  81bc4469-101e-4a30-9371-7a52a2770593  7f7f27e2-c4ee-485b-89ef-6030be6ef03b  715e87ff-9315-44bd-9cf1-a5cf6e011dda 2024-09-16 20:24:16.684000+00:00 2024-09-16 20:24:09.983000+00:00 2024-09-16 20:24:03.078000+00:00 2024-09-16 20:23:56.763000+00:00 2024-09-16 20:23:46.304000+00:00 2024-09-16 20:23:34.265000+00:00 2024-09-16 20:23:24.377000+00:00 2024-09-16 20:23:12.806000+00:00 2024-09-16 20:23:00.228000+00:00                 0               100               100               100                 0               100               100               100               100                    6.0                    5.0                    5.0                    6.0                    9.0                    9.0                   10.0                   11.0                    9.0           0.003584           0.001861           0.001918           0.001754           0.002905           0.003344           0.002747           0.003214           0.003494
258045  26645986  kjhgvfce  e7ac35b9-7fe5-44a1-89a2-ef560fb296a3 2024-09-16 20:24:16.684000+00:00           0              6.0                      8.0          9  e75fe696-f8a6-4994-97a2-071ac422cc83  d7f5752f-7df6-4ab6-80fc-37a06bcd705b  d707f485-ed1b-4660-863b-c89a53d8093e  bc01a61d-f114-46d9-afa5-4f440af6ead4  833cbc50-f160-48d0-b280-0a41149f0296  81bc4469-101e-4a30-9371-7a52a2770593  7f7f27e2-c4ee-485b-89ef-6030be6ef03b  715e87ff-9315-44bd-9cf1-a5cf6e011dda                                  None 2024-09-16 20:24:09.983000+00:00 2024-09-16 20:24:03.078000+00:00 2024-09-16 20:23:56.763000+00:00 2024-09-16 20:23:46.304000+00:00 2024-09-16 20:23:34.265000+00:00 2024-09-16 20:23:24.377000+00:00 2024-09-16 20:23:12.806000+00:00 2024-09-16 20:23:00.228000+00:00                              NaT               100               100               100                 0               100               100               100               100              None                    5.0                    5.0                    6.0                    9.0                    9.0                   10.0                   11.0                    9.0                    NaN           0.001861           0.001918           0.001754           0.002905           0.003344           0.002747           0.003214           0.003494                NaN
258046  26645986  kjhgvfce  e75fe696-f8a6-4994-97a2-071ac422cc83 2024-09-16 20:24:09.983000+00:00         100              5.0                      7.0          8  d7f5752f-7df6-4ab6-80fc-37a06bcd705b  d707f485-ed1b-4660-863b-c89a53d8093e  bc01a61d-f114-46d9-afa5-4f440af6ead4  833cbc50-f160-48d0-b280-0a41149f0296  81bc4469-101e-4a30-9371-7a52a2770593  7f7f27e2-c4ee-485b-89ef-6030be6ef03b  715e87ff-9315-44bd-9cf1-a5cf6e011dda                                  None                                  None 2024-09-16 20:24:03.078000+00:00 2024-09-16 20:23:56.763000+00:00 2024-09-16 20:23:46.304000+00:00 2024-09-16 20:23:34.265000+00:00 2024-09-16 20:23:24.377000+00:00 2024-09-16 20:23:12.806000+00:00 2024-09-16 20:23:00.228000+00:00                              NaT                              NaT               100               100                 0               100               100               100               100              None              None                    5.0                    6.0                    9.0                    9.0                   10.0                   11.0                    9.0                    NaN                    NaN           0.001918           0.001754           0.002905           0.003344           0.002747           0.003214           0.003494                NaN                NaN
258047  26645986  kjhgvfce  d7f5752f-7df6-4ab6-80fc-37a06bcd705b 2024-09-16 20:24:03.078000+00:00         100              5.0                      6.0          7  d707f485-ed1b-4660-863b-c89a53d8093e  bc01a61d-f114-46d9-afa5-4f440af6ead4  833cbc50-f160-48d0-b280-0a41149f0296  81bc4469-101e-4a30-9371-7a52a2770593  7f7f27e2-c4ee-485b-89ef-6030be6ef03b  715e87ff-9315-44bd-9cf1-a5cf6e011dda                                  None                                  None                                  None 2024-09-16 20:23:56.763000+00:00 2024-09-16 20:23:46.304000+00:00 2024-09-16 20:23:34.265000+00:00 2024-09-16 20:23:24.377000+00:00 2024-09-16 20:23:12.806000+00:00 2024-09-16 20:23:00.228000+00:00                              NaT                              NaT                              NaT               100                 0               100               100               100               100              None              None              None                    6.0                    9.0                    9.0                   10.0                   11.0                    9.0                    NaN                    NaN                    NaN           0.001754           0.002905           0.003344           0.002747           0.003214           0.003494                NaN                NaN                NaN

[258048 rows x 53 columns]

In [113]:
input_folder = 'feature_engineered_train_parquets/'

import os
column_names_file = os.path.join(input_folder, 'feature_engineered_column_names.json')
with open(column_names_file, 'r') as f:
    column_names = json.load(f)
        
# Define target and features
target = 'CORRECTNESS'
features = column_names[16:]
print('features: ', features)

features:  ['CORRECTNESS_LAG_1', 'CORRECTNESS_LAG_2', 'CORRECTNESS_LAG_3', 'CORRECTNESS_LAG_4', 'CORRECTNESS_LAG_5', 'CORRECTNESS_LAG_6', 'CORRECTNESS_LAG_7', 'CORRECTNESS_LAG_8', 'CORRECTNESS_LAG_9', 'DURATIONSECONDS_LAG_1', 'DURATIONSECONDS_LAG_2', 'DURATIONSECONDS_LAG_3', 'DURATIONSECONDS_LAG_4', 'DURATIONSECONDS_LAG_5', 'DURATIONSECONDS_LAG_6', 'DURATIONSECONDS_LAG_7', 'DURATIONSECONDS_LAG_8', 'DURATIONSECONDS_LAG_9', 'OCCURREDAT_DIFF_1', 'OCCURREDAT_DIFF_2', 'OCCURREDAT_DIFF_3', 'OCCURREDAT_DIFF_4', 'OCCURREDAT_DIFF_5', 'OCCURREDAT_DIFF_6', 'OCCURREDAT_DIFF_7', 'OCCURREDAT_DIFF_8', 'OCCURREDAT_DIFF_9', 'LOG_OCCURREDAT_DIFF_1', 'LOG_OCCURREDAT_DIFF_2', 'LOG_OCCURREDAT_DIFF_3', 'LOG_OCCURREDAT_DIFF_4', 'LOG_OCCURREDAT_DIFF_5', 'LOG_OCCURREDAT_DIFF_6', 'LOG_OCCURREDAT_DIFF_7', 'LOG_OCCURREDAT_DIFF_8', 'LOG_OCCURREDAT_DIFF_9', 'LOG_DURATIONSECONDS', 'LOG_DURATIONSECONDS_LAG_1', 'LOG_DURATIONSECONDS_LAG_2', 'LOG_DURATIONSECONDS_LAG_3', 'LOG_DURATIONSECONDS_LAG_4', 'LOG_DURATIONSECONDS_LAG_5', 'LOG_DURATIONSECONDS_LAG_6', 'LOG_DURATIONSECONDS_LAG_7', 'LOG_DURATIONSECONDS_LAG_8', 'LOG_DURATIONSECONDS_LAG_9', 'discriminability', 'difficulty', 'guessing', 'inattention', 'discriminability_error', 'difficulty_error', 'guessing_error', 'inattention_error', 'auc_roc', 'optimal_threshold', 'tpr', 'tnr', 'skill_optimal_threshold', 'student_mean_accuracy', 'discriminability_LAG_1', 'difficulty_LAG_1', 'guessing_LAG_1', 'inattention_LAG_1', 'discriminability_error_LAG_1', 'difficulty_error_LAG_1', 'guessing_error_LAG_1', 'inattention_error_LAG_1', 'auc_roc_LAG_1', 'optimal_threshold_LAG_1', 'tpr_LAG_1', 'tnr_LAG_1', 'skill_optimal_threshold_LAG_1', 'student_mean_accuracy_LAG_1', 'discriminability_LAG_2', 'difficulty_LAG_2', 'guessing_LAG_2', 'inattention_LAG_2', 'discriminability_error_LAG_2', 'difficulty_error_LAG_2', 'guessing_error_LAG_2', 'inattention_error_LAG_2', 'auc_roc_LAG_2', 'optimal_threshold_LAG_2', 'tpr_LAG_2', 'tnr_LAG_2', 'skill_optimal_threshold_LAG_2', 'student_mean_accuracy_LAG_2', 'discriminability_LAG_3', 'difficulty_LAG_3', 'guessing_LAG_3', 'inattention_LAG_3', 'discriminability_error_LAG_3', 'difficulty_error_LAG_3', 'guessing_error_LAG_3', 'inattention_error_LAG_3', 'auc_roc_LAG_3', 'optimal_threshold_LAG_3', 'tpr_LAG_3', 'tnr_LAG_3', 'skill_optimal_threshold_LAG_3', 'student_mean_accuracy_LAG_3', 'discriminability_LAG_4', 'difficulty_LAG_4', 'guessing_LAG_4', 'inattention_LAG_4', 'discriminability_error_LAG_4', 'difficulty_error_LAG_4', 'guessing_error_LAG_4', 'inattention_error_LAG_4', 'auc_roc_LAG_4', 'optimal_threshold_LAG_4', 'tpr_LAG_4', 'tnr_LAG_4', 'skill_optimal_threshold_LAG_4', 'student_mean_accuracy_LAG_4', 'discriminability_LAG_5', 'difficulty_LAG_5', 'guessing_LAG_5', 'inattention_LAG_5', 'discriminability_error_LAG_5', 'difficulty_error_LAG_5', 'guessing_error_LAG_5', 'inattention_error_LAG_5', 'auc_roc_LAG_5', 'optimal_threshold_LAG_5', 'tpr_LAG_5', 'tnr_LAG_5', 'skill_optimal_threshold_LAG_5', 'student_mean_accuracy_LAG_5', 'discriminability_LAG_6', 'difficulty_LAG_6', 'guessing_LAG_6', 'inattention_LAG_6', 'discriminability_error_LAG_6', 'difficulty_error_LAG_6', 'guessing_error_LAG_6', 'inattention_error_LAG_6', 'auc_roc_LAG_6', 'optimal_threshold_LAG_6', 'tpr_LAG_6', 'tnr_LAG_6', 'skill_optimal_threshold_LAG_6', 'student_mean_accuracy_LAG_6', 'discriminability_LAG_7', 'difficulty_LAG_7', 'guessing_LAG_7', 'inattention_LAG_7', 'discriminability_error_LAG_7', 'difficulty_error_LAG_7', 'guessing_error_LAG_7', 'inattention_error_LAG_7', 'auc_roc_LAG_7', 'optimal_threshold_LAG_7', 'tpr_LAG_7', 'tnr_LAG_7', 'skill_optimal_threshold_LAG_7', 'student_mean_accuracy_LAG_7', 'discriminability_LAG_8', 'difficulty_LAG_8', 'guessing_LAG_8', 'inattention_LAG_8', 'discriminability_error_LAG_8', 'difficulty_error_LAG_8', 'guessing_error_LAG_8', 'inattention_error_LAG_8', 'auc_roc_LAG_8', 'optimal_threshold_LAG_8', 'tpr_LAG_8', 'tnr_LAG_8', 'skill_optimal_threshold_LAG_8', 'student_mean_accuracy_LAG_8', 'discriminability_LAG_9', 'difficulty_LAG_9', 'guessing_LAG_9', 'inattention_LAG_9', 'discriminability_error_LAG_9', 'difficulty_error_LAG_9', 'guessing_error_LAG_9', 'inattention_error_LAG_9', 'auc_roc_LAG_9', 'optimal_threshold_LAG_9', 'tpr_LAG_9', 'tnr_LAG_9', 'skill_optimal_threshold_LAG_9', 'student_mean_accuracy_LAG_9', 'LOG_sample_size', 'LOG_sample_size_LAG_1', 'LOG_sample_size_LAG_2', 'LOG_sample_size_LAG_3', 'LOG_sample_size_LAG_4', 'LOG_sample_size_LAG_5', 'LOG_sample_size_LAG_6', 'LOG_sample_size_LAG_7', 'LOG_sample_size_LAG_8', 'LOG_sample_size_LAG_9', 'difficulty_spread', 'optimal_threshold_spread', 'student_mean_accuracy_spread', 'tnr_spread', 'tpr_spread', 'mean_auc_roc', 'mean_discriminability']

In [116]:
import xgboost as xgb

# Load the model
model = xgb.Booster(model_file='models/xgb_model.json')

# Print feature importances
print('\n'.join([f"{feature}: {importance:.4f}" for feature, importance in sorted(zip(model.feature_names, model.get_score(importance_type='gain').values()), key=lambda x: x[1], reverse=True)]))

student_mean_accuracy: 4007.7588
optimal_threshold: 1553.9854
CORRECTNESS_LAG_2: 1441.7776
CORRECTNESS_LAG_3: 1254.6692
CORRECTNESS_LAG_4: 818.1498
CORRECTNESS_LAG_5: 483.5280
inattention_error: 331.7412
CORRECTNESS_LAG_6: 319.9579
inattention: 269.8668
skill_optimal_threshold_LAG_1: 231.5585
CORRECTNESS_LAG_7: 210.5800
skill_optimal_threshold: 195.9965
mean_auc_roc: 166.1845
auc_roc_LAG_2: 160.5877
DURATIONSECONDS_LAG_1: 160.0711
guessing_error: 137.9370
LOG_DURATIONSECONDS_LAG_1: 133.4908
auc_roc: 120.3979
student_mean_accuracy_LAG_2: 120.0299
student_mean_accuracy_LAG_1: 118.9107
CORRECTNESS_LAG_8: 118.0088
LOG_OCCURREDAT_DIFF_1: 110.5238
OCCURREDAT_DIFF_2: 101.9947
student_mean_accuracy_LAG_3: 100.9180
tpr: 88.9425
student_mean_accuracy_spread: 87.8632
discriminability: 87.6154
OCCURREDAT_DIFF_1: 83.9778
LOG_OCCURREDAT_DIFF_2: 83.3170
guessing: 81.5409
tpr_LAG_2: 80.6564
student_mean_accuracy_LAG_4: 76.7523
inattention_LAG_1: 72.8193
LOG_OCCURREDAT_DIFF_3: 71.9645
discriminability_LAG_1: 70.5679
tnr: 67.9112
OCCURREDAT_DIFF_3: 65.1252
inattention_LAG_2: 65.1110
CORRECTNESS_LAG_9: 64.4501
auc_roc_LAG_3: 64.3987
optimal_threshold_LAG_2: 63.7927
discriminability_LAG_5: 60.1936
optimal_threshold_LAG_4: 58.7289
guessing_error_LAG_1: 58.5037
student_mean_accuracy_LAG_5: 56.6781
difficulty: 55.7245
difficulty_error: 52.9256
OCCURREDAT_DIFF_5: 51.3157
auc_roc_LAG_5: 50.7940
auc_roc_LAG_4: 49.8412
tpr_LAG_3: 49.2332
LOG_sample_size_LAG_1: 49.1191
student_mean_accuracy_LAG_6: 48.2691
skill_optimal_threshold_LAG_2: 47.2244
optimal_threshold_LAG_3: 46.7144
difficulty_spread: 46.1694
tpr_LAG_5: 44.9216
discriminability_LAG_2: 44.7426
student_mean_accuracy_LAG_8: 44.7280
tpr_LAG_4: 44.4318
skill_optimal_threshold_LAG_4: 43.8392
difficulty_LAG_1: 43.7754
LOG_sample_size: 43.6277
discriminability_error: 43.4672
LOG_OCCURREDAT_DIFF_4: 43.0266
tnr_LAG_1: 42.2758
tpr_spread: 41.9763
discriminability_LAG_4: 41.8658
student_mean_accuracy_LAG_7: 39.9608
auc_roc_LAG_6: 39.5164
DURATIONSECONDS_LAG_2: 39.4989
guessing_LAG_1: 38.5313
OCCURREDAT_DIFF_4: 35.4110
guessing_error_LAG_4: 33.9469
auc_roc_LAG_7: 32.9889
inattention_LAG_3: 32.8135
discriminability_error_LAG_5: 32.3412
mean_discriminability: 31.8493
skill_optimal_threshold_LAG_5: 31.7052
skill_optimal_threshold_LAG_3: 31.2833
OCCURREDAT_DIFF_6: 31.0039
optimal_threshold_LAG_5: 30.1632
difficulty_LAG_2: 29.9050
discriminability_error_LAG_4: 29.8107
inattention_error_LAG_2: 29.6383
tpr_LAG_1: 28.5351
LOG_DURATIONSECONDS_LAG_2: 26.4186
inattention_LAG_4: 24.8541
optimal_threshold_spread: 24.8394
discriminability_error_LAG_2: 24.7107
DURATIONSECONDS_LAG_3: 24.2970
discriminability_error_LAG_1: 23.7339
discriminability_error_LAG_6: 22.7720
inattention_error_LAG_3: 22.5817
optimal_threshold_LAG_7: 22.5278
optimal_threshold_LAG_6: 22.5145
LOG_DURATIONSECONDS_LAG_3: 22.4841
discriminability_LAG_6: 22.3596
tnr_spread: 22.0785
discriminability_LAG_3: 21.8888
LOG_sample_size_LAG_4: 21.5625
difficulty_LAG_4: 21.5613
LOG_OCCURREDAT_DIFF_5: 21.5158
guessing_LAG_2: 21.4944
difficulty_LAG_3: 21.4939
inattention_LAG_5: 21.3535
inattention_error_LAG_1: 20.6197
LOG_sample_size_LAG_2: 20.5552
OCCURREDAT_DIFF_8: 20.1636
LOG_OCCURREDAT_DIFF_7: 20.0942
difficulty_error_LAG_1: 18.8509
auc_roc_LAG_8: 18.4728
OCCURREDAT_DIFF_7: 18.4550
student_mean_accuracy_LAG_9: 17.3211
LOG_sample_size_LAG_5: 17.1793
LOG_sample_size_LAG_3: 16.9275
skill_optimal_threshold_LAG_6: 16.7406
auc_roc_LAG_9: 16.4981
LOG_sample_size_LAG_6: 16.1722
optimal_threshold_LAG_1: 15.8390
LOG_sample_size_LAG_7: 15.6799
DURATIONSECONDS_LAG_5: 15.3711
difficulty_LAG_5: 15.3046
auc_roc_LAG_1: 15.2882
optimal_threshold_LAG_9: 15.1536
DURATIONSECONDS_LAG_4: 15.0429
LOG_OCCURREDAT_DIFF_6: 15.0173
tpr_LAG_7: 15.0011
discriminability_error_LAG_3: 14.6376
tpr_LAG_8: 14.5743
LOG_DURATIONSECONDS_LAG_4: 14.4138
LOG_sample_size_LAG_8: 14.3714
skill_optimal_threshold_LAG_9: 14.2873
guessing_error_LAG_9: 13.6978
OCCURREDAT_DIFF_9: 13.4897
skill_optimal_threshold_LAG_7: 12.2209
inattention_LAG_6: 11.8411
guessing_LAG_3: 11.4629
guessing_error_LAG_2: 11.4574
tnr_LAG_2: 11.3459
difficulty_error_LAG_2: 11.1710
tnr_LAG_3: 11.1136
guessing_error_LAG_5: 11.0090
discriminability_LAG_7: 10.9695
difficulty_error_LAG_3: 10.8312
guessing_error_LAG_7: 10.7464
LOG_DURATIONSECONDS_LAG_5: 10.5988
skill_optimal_threshold_LAG_8: 10.5593
difficulty_error_LAG_8: 10.0816
tnr_LAG_4: 10.0792
discriminability_error_LAG_7: 10.0121
guessing_LAG_4: 9.4301
optimal_threshold_LAG_8: 9.4152
difficulty_error_LAG_4: 9.3199
LOG_DURATIONSECONDS_LAG_6: 9.0659
difficulty_error_LAG_7: 8.9208
tpr_LAG_6: 8.9096
guessing_error_LAG_6: 8.8555
guessing_error_LAG_8: 8.8243
inattention_error_LAG_4: 8.6162
guessing_error_LAG_3: 8.3295
inattention_error_LAG_5: 8.2888
guessing_LAG_6: 8.2249
difficulty_error_LAG_9: 8.0998
discriminability_error_LAG_8: 8.0063
LOG_DURATIONSECONDS_LAG_9: 7.8940
discriminability_LAG_8: 7.8307
DURATIONSECONDS_LAG_6: 7.7623
LOG_sample_size_LAG_9: 7.7615
DURATIONSECONDS_LAG_8: 7.7245
LOG_OCCURREDAT_DIFF_8: 7.6465
difficulty_error_LAG_5: 7.5443
difficulty_LAG_7: 7.5167
difficulty_LAG_6: 7.4931
guessing_LAG_7: 7.3439
difficulty_LAG_9: 7.2939
difficulty_LAG_8: 7.2713
guessing_LAG_9: 7.0996
LOG_OCCURREDAT_DIFF_9: 7.0085
inattention_LAG_7: 6.9606
guessing_LAG_5: 6.7508
tpr_LAG_9: 6.7417
guessing_LAG_8: 6.6711
LOG_DURATIONSECONDS_LAG_7: 6.6402
discriminability_error_LAG_9: 6.4992
inattention_error_LAG_8: 6.4752
tnr_LAG_6: 6.3145
DURATIONSECONDS_LAG_7: 6.2828
tnr_LAG_5: 6.2467
tnr_LAG_8: 5.9837
LOG_DURATIONSECONDS_LAG_8: 5.9793
difficulty_error_LAG_6: 5.8969
inattention_error_LAG_6: 5.8259
DURATIONSECONDS_LAG_9: 5.6269
tnr_LAG_9: 5.5865
inattention_error_LAG_7: 5.3833
tnr_LAG_7: 5.2427
inattention_error_LAG_9: 5.2033
inattention_LAG_8: 5.1905
inattention_LAG_9: 4.6534
discriminability_LAG_9: 4.0812

In [119]:
# Print feature importances
for feature, importance in sorted(zip(model.feature_names, model.get_score(importance_type='gain').values()), key=lambda x: x[1], reverse=True):
    if 'OCCURREDAT_DIFF' in feature:
        print(f"{feature}: {importance:.4f}")

LOG_OCCURREDAT_DIFF_1: 110.5238
OCCURREDAT_DIFF_2: 101.9947
OCCURREDAT_DIFF_1: 83.9778
LOG_OCCURREDAT_DIFF_2: 83.3170
LOG_OCCURREDAT_DIFF_3: 71.9645
OCCURREDAT_DIFF_3: 65.1252
OCCURREDAT_DIFF_5: 51.3157
LOG_OCCURREDAT_DIFF_4: 43.0266
OCCURREDAT_DIFF_4: 35.4110
OCCURREDAT_DIFF_6: 31.0039
LOG_OCCURREDAT_DIFF_5: 21.5158
OCCURREDAT_DIFF_8: 20.1636
LOG_OCCURREDAT_DIFF_7: 20.0942
OCCURREDAT_DIFF_7: 18.4550
LOG_OCCURREDAT_DIFF_6: 15.0173
OCCURREDAT_DIFF_9: 13.4897
LOG_OCCURREDAT_DIFF_8: 7.6465
LOG_OCCURREDAT_DIFF_9: 7.0085

In [ ]:
# Print feature importances
for feature, importance in sorted(zip(model.feature_names, model.get_score(importance_type='gain').values()), key=lambda x: x[1], reverse=True):
    if 'OCCURREDAT_DIFF' in feature:
        print(f"{feature}: {importance:.4f}")